---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n41stu5/public_html/
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp dist/robots.txt $DEPLOYPATH
    - /bin/cp dist/sitemap.xml $DEPLOYPATH
    - /bin/cp -R dist/assets $DEPLOYPATH
    - /bin/cp -R dist/pages $DEPLOYPATH
